FROM python:3.9-slim

# Install necessary dependencies
RUN pip install confluent-kafka

# Copy the scripts to the container in the correct folder
COPY ./consumers /app/consumers

# Working directory
WORKDIR /app/consumers
